//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFul.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Todo
    {
        public int TodoID { get; set; }
        public string TodoTile { get; set; }
        public string TodoDetails { get; set; }
        public string TodoDate { get; set; }
        public string TodoTime { get; set; }
        public int TodoUpdate { get; set; }
    }
}
